DEBUG 2018-09-14 00:19:29,986: 	 Executing command: 'submit'
DEBUG 2018-09-14 00:19:29,988: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
DEBUG 2018-09-14 00:19:30,058: 	 Checking credentials
DEBUG 2018-09-14 00:19:30,060: 	 Found proxy file /tmp/x509up_u50765
DEBUG 2018-09-14 00:19:30,060: 	 Getting proxy life time left
DEBUG 2018-09-14 00:19:31,068: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50765 -timeleft
 output : 31110

 error: 
 retcode : 0
DEBUG 2018-09-14 00:19:32,076: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50765 -actimeleft
 output : 31110

 error: 
 retcode : 0
DEBUG 2018-09-14 00:19:32,077: 	 Proxy valid for 08:38:30 hours
INFO 2018-09-14 00:19:32,077: 	 Will use CRAB configuration file crab_step1.py
DEBUG 2018-09-14 00:19:32,077: 	 Loading CRAB configuration file.
ERROR 2018-09-14 00:19:39,294: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: 'step0_ttbar_p8_02'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-09-14 00:19:39,294: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: 'step0_ttbar_p8_02'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-09-14 16:30:36,549: 	 Executing command: 'status'
DEBUG 2018-09-14 16:30:36,549: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
DEBUG 2018-09-14 20:06:59,795: 	 Executing command: 'submit'
DEBUG 2018-09-14 20:06:59,795: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
DEBUG 2018-09-14 20:08:19,133: 	 Executing command: 'submit'
DEBUG 2018-09-14 20:08:19,133: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
DEBUG 2018-09-14 20:08:19,144: 	 Checking credentials
DEBUG 2018-09-14 20:08:19,144: 	 Found proxy file /tmp/x509up_u50765
DEBUG 2018-09-14 20:08:19,144: 	 Getting proxy life time left
ERROR 2018-09-14 20:08:19,446: 	 Keyboard Interrupted
DEBUG 2018-09-20 21:54:15,241: 	 Executing command: 'resubmit'
DEBUG 2018-09-20 21:54:15,241: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
DEBUG 2018-10-29 04:11:54,949: 	 Executing command: 'kill'
DEBUG 2018-10-29 04:11:54,949: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
ERROR 2018-10-29 04:11:54,949: 	 Error: crab_projects/crab_open_qcd_p8_step1_03 is not a valid CRAB project directory.
ERROR 2018-10-29 04:11:54,949: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_open_qcd_p8_step1_03 is not a valid CRAB project directory.
DEBUG 2018-11-02 20:12:44,961: 	 Executing command: 'kill'
DEBUG 2018-11-02 20:12:44,963: 	 Found CRAB cache file /afs/cern.ch/user/e/eusai/.crab3
ERROR 2018-11-02 20:12:44,995: 	 Error: crab_projects/crab_step2_qcd_p8_0 is not a valid CRAB project directory.
ERROR 2018-11-02 20:12:44,995: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 55, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_step2_qcd_p8_0 is not a valid CRAB project directory.
